services:
  postgres:
    image: postgres:latest
    container_name: postgres-docker
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: order_service
    ports:
      - "5436:5432"
    volumes:
      - ./docker/postgresql/:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
